// <auto-generated />
namespace BoozewasherApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CreateTables_ServiceSummaryTransactionVehicle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateTables_ServiceSummaryTransactionVehicle));
        
        string IMigrationMetadata.Id
        {
            get { return "202011301018204_CreateTables_ServiceSummaryTransactionVehicle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
